name: Release Workflow

on:
  push:
    branches:
      - test

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and package
        run: |
          # Your build commands here
          # Example: go build, npm install, etc.

      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: wallee.zip
          tag_name: ${{ github.ref }}
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          name: wallee.zip
