name: Release Workflow

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and package
        run: |
          # Your build commands here
          # Example: go build, npm install, etc.

          # Ensure that 'wallee.zip' is created in the root directory
          # If it's created in a subdirectory, adjust the file path accordingly
          pwd

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: wallee.zip
          asset_name: wallee.zip
          tag: ${{ github.ref }}

