name: Release Workflow

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Get upload_url"
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
        id: release

      - name: "Upload zip"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.STAABM_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_content_type: "application/zip"
          asset_name: "wallee.zip"
          asset_path: "wallee.zip"
          upload_url: ${{ steps.release.outputs.upload_url }}

