name: Release Workflow

on:
  push:
    branches:
      - test

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Upload binaries to Github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ GITHUB_WORKSPACE }}/wallee.zip
          asset_name: wallee.zip
          tag: ${{ github.ref }}
