name: Release Workflow

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Upload binaries to Github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./wallee.zip
          asset_name: wallee.zip
          tag: ${{ github.ref }}
