name: Release Workflow

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Latest Release
        id: get_latest_release
        run: |
          latest_release=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/wallee-payment/prestashop-1.6/releases/latest" | \
                          jq -r .tag_name)
          echo "Latest release: $latest_release"
          echo "::set-output name=latest_release::$latest_release"

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: wallee.zip
          asset_name: wallee.zip
          tag: ${{ steps.get_latest_release.outputs.latest_release }}
